---
# author: yehe

- import_tasks: centos7_setup_tsung.yml
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
- import_tasks: ubuntu16_setup_tsung.yml
  when: ansible_distribution == "Debain"

